config/routes.rb
Rails.application.routes.draw do   

  resources :deputies, only: [:index, :new, :create, :destroy] do
    get 'responsibilities', action: :responsabilities, on: :collection, as: :responsabilities
    put 'update-access', action: :update, on: :collection, as: :update_access
    put ':id/upload-document', action: :upload_document, on: :collection, as: :upload_document
  end

  resources :contacts

  root to: 'frontend#index'
  
  get "/my-tasks/:category_permalink", to: "frontend#mytasks", as: "myunsealbox"
  get "/my-box", to: "frontend#myboxes", as: "myplan"
  get "/category/:category_id/get-subcategories", to: "frontend#get_subcategories", as: :get_subcategories
  get "subcategory/:subcategory_id/:model_name/:model_id/contacts/:contact_id/:switch", to: "frontend#get_contact", as: :get_contact
  get "change_status/:subcategory_id", to: "frontend#change_status", as: :change_status
  get "my-boxes-information/:objects", to: "frontend#get_my_plan_information", as: :my_plan_information
  get "my-boxes-report", to: "frontend#my_plan_report", as: :my_plan_report
  get "shared-boxes-report/:user_permalink", to: "frontend#shared_plan_report", as: :shared_plan_report
  get "users/:user_permalink/shared", to: "frontend#shared_plan", as: :shared_plan
  get "shared-information/:objects/:user_permalink", to: "frontend#shared_information", as: :shared_information

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index

  # -- contact_informations --
  scope "/:category_permalink/:subcategory_permalink" do
    resources :contact_informations
    resources :doctors
    resources :spouses
    resources :children
    resources :emergencies
    resources :advisors
    resources :life_insurances
    resources :attorneys
    resources :executors
    resources :guardians
    resources :life_insurences
    resources :wills
    resources :beneficiaries
    resources :obituaries
    resources :services
    resources :public_letters
    resources :other_letters
    resources :passports
    resources :drives_licenses
    resources :contact_informations
    resources :other_family_members
    resources :accounts
    resources :credit_cards
    resources :day_care_personnels
  end
  # -- contact_informations --


  scope :admin do
   
  	resources :users do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :categories do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :subcategories do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :newslatters do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :death_certificates do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :landing_pages do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
  end

  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'


end

app/models/subcategory.rb
#Generado por keppler
require 'elasticsearch/model'
class Subcategory < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  before_save :create_permalink, on: :create
  belongs_to :category
  has_many :statuses
  has_and_belongs_to_many :responsabilities
  
  
  after_commit on: [:update] do
    __elasticsearch__.index_document
  end

  def self.searching(query)
    if query
      self.search(self.query query).records.order(id: :desc)
    else
      self.order(id: :desc)
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
  end

  #armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: self.id.to_s,
      name:  self.name.to_s,
      description:  self.description.to_s,
      permalink:  self.permalink.to_s,
      category_id:  self.category_id.to_s,
    }.as_json
  end

  def create_permalink
    self.permalink = self.name.downcase.parameterize
  end

  def shared_subcategory?(user, deputy, subcategory)
    deputy = user.get_deputy deputy
    deputy.responsability.subcategories.include? subcategory
  end

  def in_plan?(user)
    self.models_of_subcategory.each do |model|
      return true if model.where(user_id: user.id).count > 0
    end
    false
  end

  def self.information_empty?(user)
    all.each do |subcategory|
      subcategory.models_of_subcategory.each do |model|
        return false if model.where(user_id: user.id).count > 0
      end
    end
    true
  end

  def self.shared_information_empty?(user, deputy)
     deputy = user.get_deputy deputy
     deputy.responsability.subcategories.each do |subcategory|
      subcategory.models_of_subcategory.each do |model|
        return false if model.where(user_id: user.id).count > 0
      end
     end
     true
  end

  def models_of_subcategory
    case self.permalink
    when "about-me"
      [ContactInformation, Passport, DrivesLicense]
    when "my-family"
      [Spouse, Child, OtherFamilyMember]
    when "doctors"
      [Doctor]
    when "medical-assistants"
      [DayCarePersonnel]
    when "bank-information"
      [Account, CreditCard]
    when "my-life-insurance"
      [LifeInsurance, Beneficiary]
    when "financial-advisor"
      [Advisor]
    when "emergency-contacts"
      [Emergency]
    when "attorneys"
      [Attorney]
    when "will"
      [Will, Executor, Guardian]
    when "funeral-preference"
      [Obituary, Service]
    when "letter-to-family-friends"
      [PublicLetter, OtherLetter]
    else 
      []
    end
  end

  

end
#Subcategory.import

app/controllers/subcategories_controller.rb
#Generado con Keppler.
class SubcategoriesController < ApplicationController  
  before_filter :authenticate_user!
  before_filter :client_access_denied
  layout 'admin/application'
  load_and_authorize_resource
  before_action :set_subcategory, only: [:show, :edit, :update, :destroy]

  # GET /subcategories
  def index
    subcategories = Subcategory.searching(@query).all
    @objects, @total = subcategories.page(@current_page), subcategories.size
    redirect_to subcategories_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  # GET /subcategories/1
  def show
  end

  # GET /subcategories/new
  def new
    @subcategory = Subcategory.new
  end

  # GET /subcategories/1/edit
  def edit
  end

  # POST /subcategories
  def create
    @subcategory = Subcategory.new(subcategory_params)

    if @subcategory.save
      redirect_to @subcategory, notice: 'Subcategory was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /subcategories/1
  def update
    if @subcategory.update(subcategory_params)
      redirect_to @subcategory, notice: 'Subcategory was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /subcategories/1
  def destroy
    @subcategory.destroy
    redirect_to subcategories_url, notice: 'Subcategory was successfully destroyed.'
  end

  def destroy_multiple
    Subcategory.destroy redefine_ids(params[:multiple_ids])
    redirect_to subcategories_path(page: @current_page, search: @query), notice: "Usuarios eliminados satisfactoriamente" 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subcategory
      @subcategory = Subcategory.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def subcategory_params
      params.require(:subcategory).permit(:name, :description, :category_id)
    end
end

app/views/subcategories/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.bookmark.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list

app/views/subcategories/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to subcategories_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Back" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				= simple_form_for @subcategory do |f|
					.row
						= #f.input :name
						= f.input :description, :as => :ckeditor, label: false, input_html: { :ckeditor => { :toolbar => 'short'} }
						= #f.association :category

						.form-actions.right
							= f.button :submit, "Save", class: "btn"

app/views/subcategories/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Subcategory
			= link_to edit_subcategory_path(@subcategory), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Edit", "data-no-turbolink"=> true do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.bookmark.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.name")
			.display-value= @subcategory.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.description")
			.display-value= @subcategory.description
	

:javascript
	$(".modal-trigger").leanModal();
	$('.tooltipped').tooltip({delay: 1});

app/views/subcategories/_listing.html.haml
%tr{ id: "row-#{subcategory.id}" }
	- if can? :destroy_multiple, Subcategory
		%td.item-check{style:"width: 10%"}
			= link_to "", subcategory_path(subcategory), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{subcategory.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{subcategory.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{subcategory.id}" }

	%td{style:"width: 90%"}
		= link_to "", subcategory_path(subcategory, search: @query), remote: true, class: "show-row"
		%span
			= subcategory.name
								
	%td{style:"width: 5%"}		
		= link_to subcategory_path(subcategory), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/subcategories/edit.html.haml
= title "Subcategories - edit | #{@subcategory.id}"
= render 'form'

app/views/subcategories/index.html.haml
= title("Subcategories - List")
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_subcategory_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |subcategory|
				= render 'listing', subcategory: subcategory
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado subcategories.
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_subcategory_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
		= material_icon.md_24.add.css_class("md-light")

app/views/subcategories/new.html.haml
= title "Subcategories - New"
= render 'form'

app/views/subcategories/show.html.haml
= title "Subcategories | #{@subcategory.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Subcategory
				= link_to subcategory_path(@subcategory), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Delete", method: :delete, data: { confirm: 'Are you sure?' } do
					= material_icon.md_18.delete.css_class("md-dark")	
			- if can? :update, Subcategory
				= link_to edit_subcategory_path(@subcategory), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Edit" do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to subcategories_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Back" do
				= material_icon.md_18.arrow_back.css_class("md-dark") 
		.card			
			%ul.list
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.name")
					.display-value.fs-body-1.tc-black-2= @subcategory.name.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.description")
					.display-value.fs-body-1.tc-black-2= @subcategory.description.to_s.humanize

app/views/subcategories/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@subcategory.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");