config/routes.rb
Rails.application.routes.draw do   

  resources :deputies, only: [:index, :new, :create, :destroy] do
    get 'responsibilities', action: :responsabilities, on: :collection, as: :responsabilities
    put 'update-access', action: :update, on: :collection, as: :update_access
    put ':id/upload-document', action: :upload_document, on: :collection, as: :upload_document
  end

  resources :contacts

  root to: 'frontend#index'
  
  get "/my-tasks/:category_permalink", to: "frontend#mytasks", as: "myunsealbox"
  get "/my-box", to: "frontend#myboxes", as: "myplan"
  get "/category/:category_id/get-subcategories", to: "frontend#get_subcategories", as: :get_subcategories
  get "subcategory/:subcategory_id/:model_name/:model_id/contacts/:contact_id/:switch", to: "frontend#get_contact", as: :get_contact
  get "change_status/:subcategory_id", to: "frontend#change_status", as: :change_status
  get "my-boxes-information/:objects", to: "frontend#get_my_plan_information", as: :my_plan_information
  get "my-boxes-report", to: "frontend#my_plan_report", as: :my_plan_report
  get "shared-boxes-report/:user_permalink", to: "frontend#shared_plan_report", as: :shared_plan_report
  get "users/:user_permalink/shared", to: "frontend#shared_plan", as: :shared_plan
  get "shared-information/:objects/:user_permalink", to: "frontend#shared_information", as: :shared_information

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index

  # -- contact_informations --
  scope "/:category_permalink/:subcategory_permalink" do
    resources :contact_informations
    resources :doctors
    resources :spouses
    resources :children
    resources :emergencies
    resources :advisors
    resources :life_insurances
    resources :attorneys
    resources :executors
    resources :guardians
    resources :life_insurences
    resources :wills
    resources :beneficiaries
    resources :obituaries
    resources :services
    resources :public_letters
    resources :other_letters
    resources :passports
    resources :drives_licenses
    resources :contact_informations
    resources :other_family_members
    resources :accounts
    resources :credit_cards
    resources :day_care_personnels
  end
  # -- contact_informations --


  scope :admin do
   
  	resources :users do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :categories do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :subcategories do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :newslatters do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :death_certificates do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :landing_pages do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
  end

  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'


end

app/models/credit_card.rb
class CreditCard < ActiveRecord::Base
  belongs_to :contact
  belongs_to :user
	accepts_nested_attributes_for :contact
end

app/controllers/credit_cards_controller.rb
#Generado con Keppler.
class CreditCardsController < ApplicationController  
  before_filter :authenticate_user!
  layout 'layouts/frontend/application'
  before_action :set_credit_card, only: [:show, :edit, :update, :destroy]
  before_filter :set_subcategory

  # GET /credit_cards
  def index
    @contacts = Contact.where(user_id: current_user.id).order(first_name: :asc)
    @credit_card = CreditCard.new
    @credit_cards = CreditCard.where(user_id: current_user.id).page params[:page]
  end

  # GET /credit_cards/1
  def show
  end

  # GET /credit_cards/new
  def new
    @credit_card = CreditCard.new
  end

  # GET /credit_cards/1/edit
  def edit
  end

  # POST /credit_cards
  def create
    @credit_card = CreditCard.new(credit_card_params)
    @credit_card.user_id = current_user.id
    respond_to do |format|
      if @credit_card.save
        format.html { redirect_to credit_cards_path(@subcategory.category.permalink, @subcategory.permalink), notice: 'credit_card was successfully created.' }
        format.json { render :show, status: :created, location: @credit_card }
      else
        format.html { render :new }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credit_cards/1
  def update
    case params[:commit]
    when "Save Information"
      respond_to do |format|
        if @credit_card.update(restructuring_parameters(@credit_card, credit_card_params))
          format.html { redirect_to credit_cards_path(@subcategory.category.permalink, @subcategory.permalink), notice: 'credit_card was successfully updated.' }
          format.json { render :show, status: :ok, location: @credit_card }
        else
          format.html { render :edit }
          format.json { render json: @credit_card.errors, status: :unprocessable_entity }
        end
      end
    when "Select this contact"
      @credit_card.update_attributes(contact_id: credit_card_params[:contact_id])
      redirect_to credit_cards_path(@subcategory.category.permalink, @subcategory.permalink), notice: 'Contact was successfully updated.'
    when "Delete"
      @credit_card.update_attributes(contact_id: nil)
      redirect_to credit_cards_path(@subcategory.category.permalink, @subcategory.permalink), notice: 'Contact was successfully updated.'
    end
  end

  # DELETE /credit_cards/1
  def destroy    
    @credit_card.destroy
    respond_to do |format|
      format.html { redirect_to credit_cards_path(@subcategory.category.permalink, @subcategory.permalink), notice: 'credit_card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit_card
      @credit_card = CreditCard.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def credit_card_params
      params.require(:credit_card).permit(:type_of_card, :what_type_of_card_it, :card_number, :expiration_date, :note_and_instructions, :contact_id, :user_id, contact_attributes: [:id, :first_name, :middle_name, :last_name, :birth_date, :phone_number, :email, :address, :city, :state, :zip, :country, :notes])
    end
end

app/views/credit_cards/_contact_modal.html.haml
.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1", id: "contact-modal-#{credit_card.id}"}
	= simple_form_for credit_card, url: credit_card_path(@subcategory.category.permalink, @subcategory.permalink, credit_card.id), method: :put, wrapper: :bootstrap do |f|
		.modal-dialog.modal-lg.contact-modal{:role => "document"}
			.modal-content
				.modal-header
					%button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
						%span{"aria-hidden" => "true"} &times;
					%h4.modal-title 
						= (credit_card.contact and credit_card.contact.created_at?) ? "Credit Card ##{credit_card.id} - Edit Contact" : "Credit Card ##{credit_card.id} - Add Contact"
				.modal-body
					.row
						.col-lg-3
							= render partial: "frontend/partials/listing_contacts", locals: { object: credit_card }
						.col-lg-9
							.form-contact
								= render template: "frontend/partials/form_new_contact",  locals: { subcategory: @subcategory, object: credit_card, contact: credit_card.contact }
				.modal-footer
					%button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
					= f.button :submit, "Save Information", class: "btn btn-unseal", id: "submit-contact-modal"
					= f.button(:submit, "Delete", class: "btn btn-unseal-delete btn-danger") if (credit_card.contact and credit_card.contact.created_at?)

:javascript
	$("#contact-modal-#{credit_card.id}").on('hide.bs.modal', function () {
		$.ajax({
			url: "/subcategory/#{@subcategory.id}/credit_card/#{credit_card.id}/contacts/nil/new-contact",
			context: document.body
		}).done(function() {
			$( this ).addClass( "done" );
		});
	});

app/views/credit_cards/_contact_show.html.haml
.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1", id: "contact-show-#{credit_card.id}"}
	.modal-dialog{:role => "document"}
		.modal-content
			.modal-header
				%button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
					%span{"aria-hidden" => "true"} &times;
				%h4.modal-title 
					= "#{credit_card.contact.first_name} #{credit_card.contact.middle_name} #{credit_card.contact.last_name}"
			.modal-body
				= render partial: "frontend/partials/information_contact", locals: { contact: credit_card.contact}
			.modal-footer
				%button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close

app/views/credit_cards/_edit_modal.html.haml
.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1", id: "modal-edit-#{credit_card.id}"}
	= simple_form_for credit_card, url: credit_card_path(@subcategory.category.permalink, @subcategory.permalink, credit_card.id), method: :put, wrapper: :bootstrap do |f|
		.modal-dialog{:role => "document"}
			.modal-content
				.modal-header
					%button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
						%span{"aria-hidden" => "true"} &times;
					%h4#myModalLabel.modal-title= "Credit Card ##{credit_card.id} - Edit"
				.modal-body
					= f.input :type_of_card, input_html: {class: "form-control"}
					= f.input :what_type_of_card_it, input_html: {class: "form-control"}
					= f.input :card_number, input_html: {class: "form-control"}
					= f.input :expiration_date, input_html: {class: "form-control"}
					= f.input :note_and_instructions, input_html: {class: "form-control"}
					= f.association :contact, input_html: {class: "form-control"}
				.modal-footer
					%button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
					= f.button :submit, "Save Information", class: "btn btn-unseal"

app/views/credit_cards/_form.html.haml
= simple_form_for @credit_card, wrapper: :bootstrap do |f|
	.modal-dialog{:role => "document"}
		.modal-content
			.modal-header
				%button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
					%span{"aria-hidden" => "true"} &times;
				%h4#myModalLabel.modal-title= "#{@subcategory.name.humanize} : My Credit Cards"
			.modal-body
				= f.input :type_of_card, collection: ["Visa", "Mastercard", "American Express", "Discover", "Dinner's Club", "JCB", "Store Card", "Other"],include_blank: "Select status", input_html: {class: "form-control", id: "type_of_card"}
				#what_type_of_card_it
					= f.input :what_type_of_card_it, label: "What type of card is it?", input_html: {class: "form-control"}
				= f.input :card_number, input_html: {class: "form-control"}
				= f.input :expiration_date, as: :date, :start_year => Date.today.year, :end_year => Date.today.year + 10
				%br
				= f.input :note_and_instructions, input_html: {class: "form-control"}
			.modal-footer
				%button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
				= f.button :submit, "Save", class: "btn btn-unseal"
:javascript
	$("#what_type_of_card_it").hide();
	$("#type_of_card").change(function() {
		if($("#type_of_card option:selected").text() == "Other"){
			$("#what_type_of_card_it").show();
		}else{
			$("#what_type_of_card_it").hide();
		} 
	});

app/views/credit_cards/_modal.html.haml
#myModal.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
	= render "form"

app/views/credit_cards/_show.html.haml
= title "Credit_cards | #{@credit_card.id}"	
- @credit_card.as_json(except: [:id, :user_id, :created_at, :updated_at]).each do |attribute, value|		
	- if @credit_card.contact and attribute.eql?("contact_id")
		.row-item
			%label= "#{attribute.humanize}:"
			.item
				= link_to "#", "data-target" => "#contact-show-#{@credit_card.id}", "data-toggle" => "modal" do
					= "#{@credit_card.contact.first_name} #{@credit_card.contact.last_name}"	
	- elsif !attribute.eql?("contact_id")
		- if attribute.eql?("what_type_of_card_it")
			- if @credit_card.type_of_card.eql?("Other")
				.row-item
					%label= "What type of card is it?:"
					.item= value.blank? ? "No information" : value
		- else
			.row-item
				%label= "#{attribute.humanize}:"
				.item= value.blank? ? "No information" : value

app/views/credit_cards/edit.html.haml
= title "Credit Cards - editar | #{@credit_card.id}"
= render 'form'

app/views/credit_cards/index.html.haml
= title("Credit Cards ")
%h1.title-module 
	My Credit Cards 
.container.index.card
	= render "layouts/frontend/breadcrumbs", module_name: "Credit cards"
	%ul.nav.nav-tabs{:role => "tablist"}
		%li.text-unseal.active{:role => "presentation"}
			%a{"aria-controls" => "form", "data-toggle" => "tab", :href => "#form", :role => "tab"} Add Credit Cards  Info to My Box
	.tab-content
		#form.tab-pane.active{:role => "tabpanel" }
			.card-body
				%ul.nav.nav-pills.nav-unseal
					%li.active{role:"presentation"}
						%a{"data-target" => "#myModal", "data-toggle" => "modal", :type => "button", id: "add"}
							+ Add Credit Card
				.row
					.col-lg-7.col-md-7.col-sm-6.col-xs-12.listing
						- @credit_cards.each_with_index do |credit_card, index|
							.panel.panel-default
								.panel-body{id: "panel-#{credit_card.id}"}
									= link_to credit_card_path(@subcategory.category.permalink, @subcategory.permalink, credit_card), remote: true, class: "hidden-xs" do 
										- if credit_card.type_of_card.eql?("Other") 
											= credit_card.what_type_of_card_it.blank? ? "No information" : credit_card.what_type_of_card_it
										- else
											= credit_card.type_of_card.blank? ? "No information" : credit_card.type_of_card
									
									= link_to credit_card_path(@subcategory.category.permalink, @subcategory.permalink, credit_card), class: "visible-xs" do 
										= "credit_card #{index+1}"
									.panel-actions										
										= link_to "#", "data-target" => "#contact-modal-#{credit_card.id}", "data-toggle" => "modal", class: "btn btn-unseal" do
											.fa.fa-user
											= credit_card.contact ? 'Edit Contact' : 'Add Contact'
										= link_to "#", "data-target" => "#modal-edit-#{credit_card.id}", "data-toggle" => "modal", class: "btn btn-unseal-gray", title: "Edit #{controller_name.singularize.humanize}" do
											.fa.fa-pencil-square-o
										= link_to "/#{@subcategory.category.permalink}/#{@subcategory.permalink}/credit_cards/#{credit_card.id}", method: :delete, class: "btn btn-danger", title: "Delete #{controller_name.singularize.humanize}", "data-confirm"=> "Are you sure?" do
											.fa.fa-trash
								= render "edit_modal", credit_card: credit_card
								= render "contact_modal", credit_card: credit_card
								= render "contact_show", credit_card: credit_card if credit_card.contact
						%center
							= paginate @credit_cards , :views_prefix => 'kaminari/bootstrap3'
						= render "modal"
					.col-lg-5.col-md-5.col-sm-6.hidden-xs
						.well
							.show
								= raw(@subcategory.description)

app/views/credit_cards/new.html.haml
= title "Credit Cards - New"
= render 'form'

app/views/credit_cards/show.html.haml
= title "Credit Card | #{@credit_card.id}"
= render "layouts/frontend/breadcrumbs", module_name: "My Credit_cards"
.well
	.show
		= render "show"

app/views/credit_cards/show.js.haml
$('.panel-default').find('.bg-selection').first().removeClass('bg-selection'); // remove bg-selection
$("#panel-#{@credit_card.id}").addClass('bg-selection'); // add bg-selection
$('.show').html("#{escape_javascript(render 'show')}");