config/routes.rb
Rails.application.routes.draw do   

  resources :deputies, only: [:index, :new, :create, :destroy] do
    get 'responsibilities', action: :responsabilities, on: :collection, as: :responsabilities
    put 'update-access', action: :update, on: :collection, as: :update_access
    put ':id/upload-document', action: :upload_document, on: :collection, as: :upload_document
  end

  resources :contacts

  root to: 'frontend#index'
  
  get "/my-tasks/:category_permalink", to: "frontend#mytasks", as: "myunsealbox"
  get "/my-box", to: "frontend#myboxes", as: "myplan"
  get "/category/:category_id/get-subcategories", to: "frontend#get_subcategories", as: :get_subcategories
  get "subcategory/:subcategory_id/:model_name/:model_id/contacts/:contact_id/:switch", to: "frontend#get_contact", as: :get_contact
  get "change_status/:subcategory_id", to: "frontend#change_status", as: :change_status
  get "my-boxes-information/:objects", to: "frontend#get_my_plan_information", as: :my_plan_information
  get "my-boxes-report", to: "frontend#my_plan_report", as: :my_plan_report
  get "shared-boxes-report/:user_permalink", to: "frontend#shared_plan_report", as: :shared_plan_report
  get "users/:user_permalink/shared", to: "frontend#shared_plan", as: :shared_plan
  get "shared-information/:objects/:user_permalink", to: "frontend#shared_information", as: :shared_information

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index

  # -- contact_informations --
  scope "/:category_permalink/:subcategory_permalink" do
    resources :contact_informations
    resources :doctors
    resources :spouses
    resources :children
    resources :emergencies
    resources :advisors
    resources :life_insurances
    resources :attorneys
    resources :executors
    resources :guardians
    resources :life_insurences
    resources :wills
    resources :beneficiaries
    resources :obituaries
    resources :services
    resources :public_letters
    resources :other_letters
    resources :passports
    resources :drives_licenses
    resources :contact_informations
    resources :other_family_members
    resources :accounts
    resources :credit_cards
    resources :day_care_personnels
  end
  # -- contact_informations --


  scope :admin do
   
  	resources :users do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :categories do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :subcategories do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :newslatters do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :death_certificates do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :landing_pages do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
  end

  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'


end

app/models/advisor.rb
class Advisor < ActiveRecord::Base
  belongs_to :user
  belongs_to :contact
  accepts_nested_attributes_for :contact
end

app/controllers/advisors_controller.rb
#Generado con Keppler.
class AdvisorsController < ApplicationController  
  before_filter :authenticate_user!
  layout 'layouts/frontend/application'
  before_action :set_advisor, only: [:show, :edit, :update, :destroy]
  before_filter :set_subcategory

  # GET /advisors
  def index
    @contacts = Contact.where(user_id: current_user.id).order(first_name: :asc)
    @advisor = Advisor.new
    @advisors = Advisor.where(user_id: current_user.id).page params[:page]
  end

  # GET /advisors/1
  def show
  end

  # GET /advisors/new
  def new
    @advisor = Advisor.new
  end

  # GET /advisors/1/edit
  def edit
  end

  # POST /advisors
  def create
    @advisor = Advisor.new(advisor_params)
    @advisor.user_id = current_user.id
    respond_to do |format|
      if @advisor.save
        format.html { redirect_to advisors_path(@subcategory.category.permalink, @subcategory.permalink), notice: 'advisor was successfully created.' }
        format.json { render :show, status: :created, location: @advisor }
      else
        format.html { render :new }
        format.json { render json: @advisor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advisors/1
  def update
    case params[:commit]
    when "Save Information"
      respond_to do |format|
        if @advisor.update(restructuring_parameters(@advisor, advisor_params))
          format.html { redirect_to advisors_path(@subcategory.category.permalink, @subcategory.permalink), notice: 'advisor was successfully updated.' }
          format.json { render :show, status: :ok, location: @advisor }
        else
          format.html { render :edit }
          format.json { render json: @advisor.errors, status: :unprocessable_entity }
        end
      end
    when "Select this contact"
      @advisor.update_attributes(contact_id: advisor_params[:contact_id])
      redirect_to advisors_path(@subcategory.category.permalink, @subcategory.permalink), notice: 'Contact was successfully updated.'
    when "Delete"
      @advisor.update_attributes(contact_id: nil)
      redirect_to advisors_path(@subcategory.category.permalink, @subcategory.permalink), notice: 'Contact was successfully updated.'
    end
  end

  # DELETE /advisors/1
  def destroy    
    @advisor.destroy
    respond_to do |format|
      format.html { redirect_to advisors_path(@subcategory.category.permalink, @subcategory.permalink), notice: 'advisor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advisor
      @advisor = Advisor.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def advisor_params
      params.require(:advisor).permit(:type_of_advisor, :notes, :user_id, :contact_id, contact_attributes: [:id, :first_name, :middle_name, :last_name, :birth_date, :phone_number, :email, :address, :city, :state, :zip, :country, :notes])
    end
end

app/views/advisors/_contact_modal.html.haml
.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1", id: "contact-modal-#{advisor.id}"}
	= simple_form_for advisor, url: advisor_path(@subcategory.category.permalink, @subcategory.permalink, advisor.id), method: :put, wrapper: :bootstrap do |f|
		.modal-dialog.modal-lg.contact-modal{:role => "document"}
			.modal-content
				.modal-header
					%button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
						%span{"aria-hidden" => "true"} &times;
					%h4.modal-title 
						= (advisor.contact and advisor.contact.created_at?) ? "Advisor ##{advisor.id} - Edit Contact" : "Advisor ##{advisor.id} - Add Contact"
				.modal-body
					.row
						.col-lg-3
							= render partial: "frontend/partials/listing_contacts", locals: { object: advisor }
						.col-lg-9
							.form-contact
								= render template: "frontend/partials/form_new_contact",  locals: { subcategory: @subcategory, object: advisor, contact: advisor.contact }
				.modal-footer
					%button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
					= f.button :submit, "Save Information", class: "btn btn-unseal", id: "submit-contact-modal"
					= f.button(:submit, "Delete", class: "btn btn-unseal-delete btn-danger") if (advisor.contact and advisor.contact.created_at?)

:javascript
	$("#contact-modal-#{advisor.id}").on('hide.bs.modal', function () {
		$.ajax({
			url: "/subcategory/#{@subcategory.id}/advisor/#{advisor.id}/contacts/nil/new-contact",
			context: document.body
		}).done(function() {
			$( this ).addClass( "done" );
		});
	});

app/views/advisors/_contact_show.html.haml
.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1", id: "contact-show-#{advisor.id}"}
	.modal-dialog{:role => "document"}
		.modal-content
			.modal-header
				%button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
					%span{"aria-hidden" => "true"} &times;
				%h4.modal-title 
					= "#{advisor.contact.first_name} #{advisor.contact.middle_name} #{advisor.contact.last_name}"
			.modal-body
				= render partial: "frontend/partials/information_contact", locals: { contact: advisor.contact}
			.modal-footer
				%button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close

app/views/advisors/_edit_modal.html.haml
.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1", id: "modal-edit-#{advisor.id}"}
	= simple_form_for advisor, url: advisor_path(@subcategory.category.permalink, @subcategory.permalink, advisor.id), method: :put, wrapper: :bootstrap do |f|
		.modal-dialog{:role => "document"}
			.modal-content
				.modal-header
					%button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
						%span{"aria-hidden" => "true"} &times;
					%h4#myModalLabel.modal-title= "Advisor ##{advisor.id} - Edit"
				.modal-body
					= f.input :type_of_advisor, collection: ["Accountant", "Financial Planner", "Insurance Advisor", "Investment Manager", "Tax Preparer", "Other"],include_blank: "", input_html: {class: "form-control"}
					= f.input :notes, input_html: {class: "form-control"}
				.modal-footer
					%button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
					= f.button :submit, "Save Information", class: "btn btn-unseal"

app/views/advisors/_form.html.haml
= simple_form_for @advisor, wrapper: :bootstrap do |f|
	.modal-dialog{:role => "document"}
		.modal-content
			.modal-header
				%button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
					%span{"aria-hidden" => "true"} &times;
				%h4#myModalLabel.modal-title= "#{@subcategory.name.humanize} : My Advisors"
			.modal-body
				= f.input :type_of_advisor, collection: ["Accountant", "Financial Planner", "Insurance Advisor", "Investment Manager", "Tax Preparer", "Other"],include_blank: "", input_html: {class: "form-control"}
				= f.input :notes, input_html: {class: "form-control"}
			.modal-footer
				%button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
				= f.button :submit, "Save", class: "btn btn-unseal"

app/views/advisors/_modal.html.haml
#myModal.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
	= render "form"

app/views/advisors/_show.html.haml
= title "Advisors | #{@advisor.id}"	
- @advisor.as_json(except: [:id, :user_id, :created_at, :updated_at]).each do |attribute, value|
	.row-item	
		- if @advisor.contact and attribute.eql?("contact_id")
			%label= "#{attribute.humanize}:"
			.item
				= link_to "#", "data-target" => "#contact-show-#{@advisor.id}", "data-toggle" => "modal" do
					= "#{@advisor.contact.first_name} #{@advisor.contact.last_name}"	
		- elsif !attribute.eql?("contact_id")
			%label= "#{attribute.humanize}:"
			.item= value.blank? ? "No information" : value

app/views/advisors/edit.html.haml
= title "Advisors - editar | #{@advisor.id}"
= render 'form'

app/views/advisors/index.html.haml
= title("Advisors ")
%h1.title-module 
	My Advisors 
.container.index.card
	= render "layouts/frontend/breadcrumbs", module_name: "Advisors"
	%ul.nav.nav-tabs{:role => "tablist"}
		%li.text-unseal.active{:role => "presentation"}
			%a{"aria-controls" => "form", "data-toggle" => "tab", :href => "#form", :role => "tab"} Add Advisors  Info to My Box
	.tab-content
		#form.tab-pane.active{:role => "tabpanel" }
			.card-body
				%ul.nav.nav-pills.nav-unseal
					%li.active{role:"presentation"}
						%a{"data-target" => "#myModal", "data-toggle" => "modal", :type => "button", id: "add"}
							+ Add Advisor
				.row
					.col-lg-7.col-md-7.col-sm-6.col-xs-12.listing
						- @advisors.each_with_index do |advisor, index|
							.panel.panel-default
								.panel-body{id: "panel-#{advisor.id}"}
									= link_to advisor_path(@subcategory.category.permalink, @subcategory.permalink, advisor), remote: true, class: "hidden-xs" do 
										= advisor.contact ? "#{advisor.type_of_advisor}: #{advisor.contact.first_name} #{advisor.contact.last_name}" : "#{advisor.type_of_advisor}: You have not assigned a contact"
									= link_to advisor_path(@subcategory.category.permalink, @subcategory.permalink, advisor),class: "visible-xs" do 
										= advisor.contact ? "#{advisor.type_of_advisor}: #{advisor.contact.first_name} #{advisor.contact.last_name}" : "#{advisor.type_of_advisor}: You have not assigned a contact"
									.panel-actions										
										= link_to "#", "data-target" => "#contact-modal-#{advisor.id}", "data-toggle" => "modal", class: "btn btn-unseal" do
											.fa.fa-user
											= advisor.contact ? 'Edit Contact' : 'Add Contact'
										= link_to "#", "data-target" => "#modal-edit-#{advisor.id}", "data-toggle" => "modal", class: "btn btn-unseal-gray", title: "Edit #{controller_name.singularize.humanize}" do
											.fa.fa-pencil-square-o
										= link_to "/#{@subcategory.category.permalink}/#{@subcategory.permalink}/advisors/#{advisor.id}", method: :delete, class: "btn btn-danger", title: "Delete #{controller_name.singularize.humanize}", "data-confirm"=> "Are you sure?" do
											.fa.fa-trash
								= render "edit_modal", advisor: advisor
								= render "contact_modal", advisor: advisor
								= render "contact_show", advisor: advisor if advisor.contact
						%center
							= paginate @advisors , :views_prefix => 'kaminari/bootstrap3'
						= render "modal"
					.col-lg-5.col-md-5.col-sm-6.hidden-xs
						.well
							.show
								= raw(@subcategory.description)

app/views/advisors/new.html.haml
= title "Advisors - New"
= render 'form'

app/views/advisors/show.html.haml
= title "Advisor | #{@advisor.id}"
= render "layouts/frontend/breadcrumbs", module_name: "My Advisors"
.well
	.show
		= render "show"

app/views/advisors/show.js.haml
$('.panel-default').find('.bg-selection').first().removeClass('bg-selection'); // remove bg-selection
$("#panel-#{@advisor.id}").addClass('bg-selection'); // add bg-selection
$('.show').html("#{escape_javascript(render 'show')}");